name: Deploy to ECR

# Controls when the workflow will run

on:
  pull_request:
    branches: 
      - main
    types: [closed]
  workflow_run:
    workflows: ['Dependabot PR Check']
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.pull_request.merged }}
    name: Build Image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: cluerium_ecr_repo
          IMAGE_TAG: latest
        run: |
          docker build -f Dockerfile.multistage -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
